# Generated by Django 6.0.6 on 2026-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
    ]
